disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - trailing_whitespace
  - leading_whitespace
  - opening_brace
  - variable_name
  - nesting
  # - conditional_binding_cascade
  # - legacy_constructor
  # - legacy_cggeometry_functions
  # - colon
  # - control_statement
  # - file_length
  # - force_cast
  # - function_body_length
  # - line_length
  # - operator_whitespace
  # - return_arrow_whitespace
  # - todo
  # - type_body_length
  # - type_name
opt_in_rules: # some rules are only opt-in
  - empty_count
  # - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - marvel-universe/Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - marvel-universe/Resources
  - Pods
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 120
# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 600 # error
# or they can set both explicitly
function_body_length:
  - 80
  - 150
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  max_length: 20
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - pk
    - rv
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
