language: swift
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="marvel-universe.xcworkspace"
  - SCHEME="marvel-universe"
  - IOS_SDK=iphonesimulator10.0
  - DESTINATION="name=iPhone 7S,OS=10.0"
before_install:
  - gem install activesupport -v 4.2.6
  - gem install cocoapods -v '1.1.0.rc.2'
  - gem install bundler
install:
  - bundle install
  - pod repo remove master
  - pod setup
  - bundle exec pod install
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c
