language: swift
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="marvel-universe.xcworkspace"
  - SCHEME="marvel-universe"
  - IOS_SDK=iphonesimulator10.0
  - DESTINATION="name=iPhone 7S,OS=10.0"
before_install:
  - sudo gem update --system
  - sudo gem install activesupport -v 4.2.6
  - sudo gem install cocoapods --pre
  - sudo rm -fr ~/Library/Caches/CocoaPods/
  - sudo rm -fr ~/.cocoapods/repos/master/
  - sudo rm -fr Pods/
install:
  - pwd
  - ls -la
  - pod setup --verbose
  - pod install --verbose
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c
