language: swift
osx_image: xcode8
before_install:
  - gem install activesupport -v 4.2.6
  - gem install cocoapods --pre
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="marvel-universe.xcworkspace"
  - SCHEME="marvel-universe"
  - IOS_SDK=iphonesimulator10.0
  - DESTINATION="name=iPhone 7S,OS=10.0"
script:
  - pod install
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c
